export const en = {
  locale: "en", nav: { home: "Home", menu: "Menu", closeMenu: "Close menu", access: "Information", reserve: "Reserve" },
  hero: { eyebrow: "OSAKA ITALIAN BAR", title: "Make tonight more delicious.", body: "From a casual drink to an unhurried meal, we are an Italian bar made for Osaka evenings." },
  home: { verticalTitle: "Italian bar", heroNavLabel: "Home page navigation", heroNav: { home: "Home", about: "About", menu: "Menu", access: "Access", reservation: "Reservation" }, heroDishesAlt: "Pasta, antipasto, and carpaccio", heroScrollLabel: "Continue to the restaurant introduction", aboutLabel: "About", aboutTitle: "About Gusto", aboutBody: ["A café by day and a relaxed Italian bar by night.", "Our owner, a certified wine expert, keeps learning every day to create a bar where everyone can enjoy wine and food.", "Whether you already love wine or are just beginning to discover it,", "please feel free to stop by.", "We offer something for every budget."], aboutMore: "Read about our wine", wineLabel: "Menu", wineTitle: "About wine", wineBody: ["Wine is made by fermenting grapes. Red and white wines differ through the grapes selected and the way they are produced.", "At Gusto, we keep a varied selection so you can find a glass that suits your meal and your mood.", "Wine is meant to be enjoyed without ceremony. If you are unsure what to choose, please feel free to ask our staff."], wineMenu: "View the wine menu", wineArtworkAlt: "Illustration of a wine bottle and grapes", readMore: "Discover our wine", gallery: "Inside Gusto", galleryImageAlt: "Gusto's dining room and dishes", social: { twitter: { name: "Twitter", description: "News and updates from Gusto" }, instagram: { name: "Instagram", description: "See our latest menu additions" }, blog: { name: "Blog", description: "Notes from the owner" } }, reservationTitle: "Reservation", reservationLabel: "Reservations and inquiries", reservationNotes: ["Gusto accepts reservations online only.", "Reservations can be made until the day before your visit.", "If online reservations are full, a limited number of same-day seats may still be available. Please visit us directly; if every seat is occupied, you may enjoy the standing area until a table becomes available.", "To avoid inconveniencing other guests, reservations are limited to two hours from the booked time."], reservationCta: "Continue to reservations and inquiries", accessTitle: "Access", accessLabel: "How to find us", accessMap: "View on Google Maps", accessMapExternal: "Open Google Maps in a new tab", accessMapTitle: "Map showing the area around Gusto", accessDetails: "Access", accessRoutes: ["Osaka Metro Tanimachi Line: 1 minute from Sekime-Takadono Station, Exit 3", "Osaka Metro Imazatosuji Line: 3 minutes from Sekime-Seiiku Station, Exit 2", "Keihan Main Line: 5 minutes from Sekime Station"], paymentLabel: "Payment", paymentMethods: "Cash, VISA, Mastercard" },
  concept: { title: "An Italian table where you can unwind.", body: "Seasonal ingredients and wine, enjoyed without formality. A little extra room for a memorable evening." },
  menu: { title: "MENU", viewAll: "View menu", unavailable: "Our menu is being prepared." , excludingTax: "excl. tax", includingTax: "incl. tax" },
  featured: { title: "Our recommendation ", numberLabels: ["1", "2", "3"], menuLinks: ["View the pasta menu", "View the pizza menu", "View the à la carte menu"], previous: "Previous recommendation", next: "Next recommendation", position: "Recommendation {current} of {total}" },
  info: { title: "Visit us", address: "Address", hours: "Hours", phone: "Phone" },
  footer: { navigation: "Footer navigation", nav: { menu: "Menu", story: "Our Story", access: "Access", reservation: "Reservation" }, socialExternal: "Open {name} in a new tab", lunch: "Lunch", dinner: "Dinner", copyright: "© 2023 Masa Kondo. All Rights Reserved." },
  reserve: { title: "Reservations", body: "Reserve your table through our reservation form.", cta: "Open reservation form", external: "Opens the reservation form in a new tab", unavailable: "Our reservation form is being prepared. Please contact us by phone." },
  errors: { dynamic: "We could not load the latest information. Please try again shortly." },
  seo: { homeTitle: "Italian bar in Osaka", homeDescription: "Gusto Italian Bar, a relaxed Italian bar in Osaka.", menuTitle: "Menu", reserveTitle: "Reservations" },
} as const;
